# Generated by Django 4.2.25 on 2025-10-24 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionreport",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="submissionvote",
            index=models.Index(
                fields=["submission", "user"], name="submissions_submiss_776f55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionvote",
            index=models.Index(
                fields=["created_at"], name="submissions_created_3107bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionvote",
            unique_together={("submission", "user")},
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="submission_slug_unique_ci",
            ),
        ),
    ]
