# Generated by Django 4.2.25 on 2025-10-24 12:05

from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_submissionmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfile",
            name="file",
            field=models.FileField(upload_to=submissions.models.upload_path),
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="submissions.folder",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="submissions.folder",
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["submission", "parent", "name"],
                name="submissions_submiss_d4b447_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("submission", "parent", "name")},
        ),
    ]
