# Generated by Django 4.2.25 on 2025-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_alter_submissionfile_file_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="trending_score",
            field=models.FloatField(default=0.0),
        ),
    ]
