from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .views import RegisterView, ProfileViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'profile', ProfileViewSet, basename='profile')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # Endpoint for user registration
    path('register/', RegisterView.as_view(), name='auth_register'),

    # Endpoints for JWT token authentication (login)
    # POST to /api/users/token/ with username and password to get an access and refresh token.
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),

    # POST to /api/users/token/refresh/ with the refresh token to get a new access token.
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Include the URLs generated by the router for the ProfileViewSet
    # This will create endpoints like /api/users/profile/
    path('', include(router.urls)),
]
